app/__init__.py
from flask import Flask
from app.settings import DevelopmentConfig

def create_app():
    app = Flask(__name__) 
    app.config.from_object(DevelopmentConfig)    
    from app.routes.calculator_routes import calculator_blueprint
    app.register_blueprint(calculator_blueprint)   


    return app

app= create_app()

if __name__ == '__main__':
    app.run(debug=True)

app/routes/calculator_routes.py
import datetime
from flask import Blueprint, request, render_template, redirect, url_for, flash
from app.utils.calculator import CalculadorNutricional



calculator_blueprint = Blueprint('calculator', __name__)


@calculator_blueprint.route('/form_calculator')
def form_calculator():
    return render_template('form_calculator.html')
    

@calculator_blueprint.route('/calculate', methods=["POST"])
def calculate():
    data = request.form
    calculator = CalculadorNutricional()
    result = calculator.solucion(edad=int(data.get('age', 0)), peso=float(data.get('weight', -10)))
    if result.get('message', None):
        flash(result.get('message'))
        return redirect(url_for('calculator.form_calculator'))
    print(result)
    current_date = datetime.datetime.now()   

    return render_template('result.html', result=result, name=data.get('name', ''), current_date=current_date.strftime('%d / %m / %Y'), age=int(data.get('age', 0)), weight=float(data.get('weight', -10)))

app/templates/form_calculator.html
{% extends "layout.html" %}


{% block content %}
<div class="container mt-2">
  <h2>Calculadora nutricional para niños</h2>
  <div class="container mt-4 min-vw-60">

    <form action="{{ url_for('calculator.calculate') }}" method="POST" class="container">
      <div class="mb-3">
        <label for="name" class="form-label"><b>Nombre</b></label>
        <input type="text" class="form-control" id="name" name="name" aria-describedby="name_help" required>
      </div>
      <div class="mb-3">
        <label for="age" class="form-label"><b>Edad</b></label>
        <input type="number" min="5" max="17" class="form-control" id="age" name="age" aria-describedby="age_help"
          required>
        <div id="age_help" class="form-text">La edad debe estar entre 5 y 17</div>
      </div>
      <div class="mb-3">
        <label for="weight" class="form-label"><b>Peso</b></label>
        <input type="number" step="0.1" min="0.1" class="form-control" id="weight" name="weight"
          aria-describedby="weight_help" required>
        <div id="weight_help" class="form-text">El peso debe ser mayor a 0</div>
      </div>

      <button type="submit" class="btn btn-primary">Calcular</button>
    </form>
  </div>
</div>

{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <title>Calculador de estado nutricional</title>
</head>

<body>
    <nav class="navbar bg-body-tertiary">
        <div class="container-fluid">
            <span class="navbar-brand mb-0 h1">App calculadora nutricional para niños</span>
            <span class="navbar-text">
                BY Alvaro Andres Niño Rincon
            </span>

        </div>
    </nav>
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    <ul class=flashes>
        {% for message in messages %}
        <li>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    {% endwith %}

    {% block content %}{% endblock %}
    <div style='z-index: -10;' class="fixed-bottom"><img src="/static/img/composicion-horizontal-frutas-verduras.png" />
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous"></script>
</body>

</html>

app/templates/result.html
{% extends "layout.html" %}


{% block content %}
<div class="container mt-2">
    <h2>Estado nutricional</h2>
    <div class="container mt-4">
        <p>Fecha: <b>{{current_date}}</b></p>
        <p>Paciente <b>{{name}}</b> con edad <b>{{age}}</b> y peso <b>{{weight}} kg </b>presenta
            <b>{{result['situacion_nutricional_actual']['tipo']}}</b>.
        </p>
        <p>Se sugiere la siguiente receta diaria
            {% if result['situacion_nutricional_actual']['tipo'] != 'peso saludable' %}<span><b>{{result['dias']}}</b>
                por dias para obtener el peso de
                <b>{{result['situacion_nutricional_actual']['objetivo']}} kg</b>.</span>{% endif %}
        </p>

        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Grupos nutricionales</th>
                    <th scope="col"># Porciones</th>
                    <th scope="col">Cantidad(gramos)</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th scope="row">Carbohidratos</th>
                    <td>{{result['receta']['porciones']['pc']}}</td>
                    <td>{{result['receta']['cantidad']['c']*1000}}</td>
                </tr>
                <tr>
                    <th scope="row">Proteina</td>
                    <td>{{result['receta']['porciones']['pp']}}</td>
                    <td>{{result['receta']['cantidad']['p']*1000}}</td>
                </tr>
                <tr>
                    <th scope="row">Verduras</td>
                    <td>{{result['receta']['porciones']['pv']}}</td>
                    <td>{{(-1)*result['receta']['cantidad']['v']*1000}}</td>
                </tr>
            </tbody>
        </table>
        <p>Tener presente agendar cita nuevamente para seguimiento.</p>
        <a href="{{url_for('calculator.form_calculator')}}" type="button" class="btn btn-secondary">Regresar</a>

    </div>
</div>


{% endblock %}